### ISSUE TITLE
Problem on getting table name/data with CR1000

### ISSUE THREAD

**Issue by bernardomjunior** [LionelDarras/PyCampbellCR1000#7]
Hi,
I'm having an issue with the method list_tables(), sometimes it works very well and sometimes do not.
Here the code that I am using:
```
from pycampbellcr1000 import CR1000
import time

# or with Serial connection
device = CR1000.from_url('serial:/dev/ttyS0:115200')

print("Device is connected: %s" %device.connected)

while True:
    tables = device.list_tables()
    print(tables)
    if len(tables) == 0:
        time.sleep(1)
    else:
        break
device.bye()
```

Outputs:
Bad one:

> Device is connected: True
> []
> []
> []
> []
> []
> []
> []
> []
> []

Good one:

> Device is connected: True
> ['Status', 'Table1', 'Table2', 'Table3', 'Public']

I looped in order to see if some time after bad outputs happens I whould receive a good one.
Is it intended for me to remake the connection with the CR1000 until I become able to receive the right answer?

**Comment by Makada-cyber** [comment]
Hi,
Im having trouble with this code also.
With your code above i get the following error:

Value=struct.unpack(str(fmt), buff[offset:offset+size])
Struct.error: unpack requires a buffer of 4 bytes

Line 318 in pakbus.py

**Comment by bernardomjunior** [comment]
sorry, but its been long since i touched a datalogger.
